# Generated by Django 5.0.2 on 2024-02-22 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesionalmodel",
            name="equipo",
        ),
    ]
