# Generated by Django 5.0.2 on 2024-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0002_remove_profesionalmodel_equipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipomodel",
            options={"verbose_name": "Equipo", "verbose_name_plural": "Equipos"},
        ),
        migrations.AlterField(
            model_name="profesionalmodel",
            name="correo",
            field=models.CharField(max_length=100, verbose_name="Correo"),
        ),
        migrations.AlterField(
            model_name="profesionalmodel",
            name="tipo_profesional",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Tipo de Profesional",
            ),
        ),
        migrations.AlterModelTable(
            name="equipomodel",
            table="Equipo",
        ),
    ]
