# Generated by Django 5.0.2 on 2024-02-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0003_alter_equipomodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrabajoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(max_length=100, verbose_name="Nombre del evento"),
                ),
                ("dia_comienzo", models.DateField(verbose_name="Dia de comienzo")),
                (
                    "dia_finalizacion",
                    models.DateField(verbose_name="Dia de finalizacion"),
                ),
                (
                    "pro_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App1.profesionalmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "Evento",
            },
        ),
    ]
